import nbformat
import os

def fix():
    nb_path = '1_NoteBook/Prediction.ipynb'
    with open(nb_path, 'r') as f:
        nb = nbformat.read(f, as_version=4)

    # We want 3 main cells:
    # 1. Imports & Config & Helpers (Setup)
    # 2. V6 Data Pipeline (Feature Engineering)
    # 3. V7 Modeling (ML Training)

    # Setup Source
    setup_source = [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import json\n",
        "import os\n",
        "import xgboost as xgb\n",
        "import lightgbm as lgb\n",
        "from sklearn.ensemble import RandomForestClassifier, VotingClassifier\n",
        "from sklearn.model_selection import TimeSeriesSplit, RandomizedSearchCV\n",
        "from sklearn.metrics import accuracy_score\n",
        "\n",
        "# Resolve Data Directory\n",
        "csv_dir = 'csv_data' if os.path.exists('csv_data') else '../csv_data'\n",
        "print(f'Using resolved CSV directory: {csv_dir}')\n",
        "\n",
        "# IGN Alias Mapping (Pillar 3 Fix)\n",
        "IGN_ALIASES = {\n",
        "    'rtzy': 'karl tzy',\n",
        "    'karl tzy': 'karl tzy',\n",
        "    'bon chan': 'bon chan',\n",
        "    'e2max': 'e2max',\n",
        "    'e2max': 'e2max',\n",
        "    'hadji': 'had ji',\n",
        "    'had ji': 'had ji',\n",
        "    'ohmyv33nus': 'ohmyv33nus',\n",
        "    'oheb': 'oheb',\n",
        "    'super marco': 'super marco',\n",
        "    'imbadeejay': 'imbadeejay',\n",
        "    'jeffqt4ever': 'jeffqt4ever',\n",
        "    'shaiderqt': 'shaiderqt',\n",
        "    'renejay': 'renejay',\n",
        "    'eson': 'eson',\n",
        "    'dex star': 'dex star',\n",
        "    'edward': 'edward',\n",
        "    'h2wo': 'h2wo',\n",
        "    'ejhay': 'ejhay',\n",
        "    'lancecy': 'lancecy'\n",
        "}\n",
        "\n",
        "def resolve_ign(ign):\n",
        "    ign = str(ign).strip().lower()\n",
        "    return IGN_ALIASES.get(ign, ign)\n",
        "\n",
        "def clean_patch_version(x):\n",
        "    x = str(x).strip()\n",
        "    if x.lower() in ('nan', 'none', ''):\n",
        "        return 'Unknown'\n",
        "    x = x.replace('–', '-')\n",
        "    return x.split('-')[-1].strip() if '-' in x else x\n"
    ]

    # Pipeline Source (Extracted from old cells)
    pipeline_source = [
        "print(\"🚀 Starting V6 Master Pipeline...\")\n",
        "\n",
        "matches_df = pd.read_csv(f'{csv_dir}/matches.csv')\n",
        "games_df   = pd.read_csv(f'{csv_dir}/games.csv')\n",
        "rosters_df = pd.read_csv(f'{csv_dir}/season_rosters.csv')\n",
        "patches_df = pd.read_csv(f'{csv_dir}/patches.csv')\n",
        "\n",
        "matches_df['match_timestamp'] = pd.to_datetime(matches_df['match_timestamp'])\n",
        "games_df['match_timestamp']   = pd.to_datetime(games_df['match_timestamp'])\n",
        "\n",
        "valid_match_ids = games_df['match_id'].unique()\n",
        "matches_df = matches_df[matches_df['match_id'].isin(valid_match_ids)]\n",
        "matches_df = matches_df[matches_df['match_timestamp'] < pd.Timestamp.now()]\n",
        "\n",
        "matches_df['patch_version'] = matches_df['patch_version'].apply(clean_patch_version)\n",
        "target_date = matches_df['match_timestamp'].max()\n",
        "matches_df['days_ago']     = (target_date - matches_df['match_timestamp']).dt.days\n",
        "matches_df['time_weight']  = np.exp(-0.002 * matches_df['days_ago'])\n",
        "matches_df['is_playoff_match'] = matches_df['stage'].str.lower().str.strip() == 'playoffs'\n",
        "\n",
        "print(\"Calculating Elo ratings (Regular + Playoff tracks)...\")\n",
        "team_rosters = {}\n",
        "for _, row in rosters_df.iterrows():\n",
        "    team, season = row['team_name'], str(row['season']).strip()\n",
        "    try:    player_igns = set([resolve_ign(p['ign']) for p in json.loads(row['players'])])\n",
        "    except: player_igns = set()\n",
        "    if team not in team_rosters: team_rosters[team] = {}\n",
        "    team_rosters[team][season] = player_igns\n",
        "\n",
        "matches_df = matches_df.sort_values('match_timestamp').reset_index(drop=True)\n",
        "player_elos = {}; player_playoff_elos = {}\n",
        "default_elo = 1500; k_regular = 32; k_playoff = 56; decay_rate = 0.15\n",
        "matches_df['team_a_elo'] = 0.0; matches_df['team_b_elo'] = 0.0\n",
        "matches_df['team_a_playoff_elo'] = 0.0; matches_df['team_b_playoff_elo'] = 0.0\n",
        "current_global_season = str(matches_df.iloc[0]['season'])\n",
        "\n",
        "def get_team_avg_elo(team_name, season_string, elo_dict):\n",
        "    roster = team_rosters.get(team_name, {}).get(season_string, set())\n",
        "    if not roster: return default_elo\n",
        "    return sum([elo_dict.get(ign, default_elo) for ign in roster]) / len(roster)\n",
        "\n",
        "for index, row in matches_df.iterrows():\n",
        "    match_season = str(row['season'])\n",
        "    is_playoff = row['is_playoff_match']\n",
        "    if match_season != current_global_season:\n",
        "        for ign in player_elos: player_elos[ign] = 1500 + ((player_elos[ign] - 1500) * (1 - decay_rate))\n",
        "        for ign in player_playoff_elos: player_playoff_elos[ign] = 1500 + ((player_playoff_elos[ign] - 1500) * (1 - decay_rate))\n",
        "        current_global_season = match_season\n",
        "    \n",
        "    elo_a = get_team_avg_elo(row['team_a_name'], match_season, player_elos)\n",
        "    elo_b = get_team_avg_elo(row['team_b_name'], match_season, player_elos)\n",
        "    p_elo_a = get_team_avg_elo(row['team_a_name'], match_season, player_playoff_elos)\n",
        "    p_elo_b = get_team_avg_elo(row['team_b_name'], match_season, player_playoff_elos)\n",
        "    \n",
        "    matches_df.at[index, 'team_a_elo'] = elo_a\n",
        "    matches_df.at[index, 'team_b_elo'] = elo_b\n",
        "    matches_df.at[index, 'team_a_playoff_elo'] = p_elo_a\n",
        "    matches_df.at[index, 'team_b_playoff_elo'] = p_elo_b\n",
        "\n",
        "    # Simplified update for features (Match-based Pillar 3 fix)\n",
        "    actual_a = 1 if row['series_score_a'] > row['series_score_b'] else 0\n",
        "    k = k_playoff if is_playoff else k_regular\n",
        "    for ign in team_rosters.get(row['team_a_name'], {}).get(match_season, set()):\n",
        "        player_elos[ign] = player_elos.get(ign, default_elo) + k * (actual_a - (1/(1+10**((elo_b-elo_a)/400))))\n",
        "        if is_playoff: player_playoff_elos[ign] = player_playoff_elos.get(ign, default_elo) + k * (actual_a - (1/(1+10**((p_elo_b-p_elo_a)/400))))\n",
        "    for ign in team_rosters.get(row['team_b_name'], {}).get(match_season, set()):\n",
        "        player_elos[ign] = player_elos.get(ign, default_elo) + k * ((1-actual_a) - (1/(1+10**((elo_a-elo_b)/400))))\n",
        "        if is_playoff: player_playoff_elos[ign] = player_playoff_elos.get(ign, default_elo) + k * ((1-actual_a) - (1/(1+10**((p_elo_a-p_elo_b)/400))))\n",
        "\n",
        "print(\"✅ V6 Data Pipeline Complete!\")\n"
    ]

    # Modeling Source
    modeling_source = [
        "print(\"\\n📊 Loading Feature Matrix for V7 Engine...\")\n",
        "df = pd.read_csv(f'{csv_dir}/ML_Feature_Matrix.csv')\n",
        "\n",
        "# Filter and engineering logic...\n",
        "df['match_timestamp'] = pd.to_datetime(df['match_timestamp'])\n",
        "df = df.sort_values(['match_timestamp', 'game_number']).reset_index(drop=True)\n",
        "\n",
        "base_features = [\n",
        "    'blue_side_elo', 'red_side_elo',\n",
        "    'blue_playoff_elo', 'red_playoff_elo',\n",
        "    'blue_comfort_wr', 'red_comfort_wr',\n",
        "    'blue_draft_experience', 'red_draft_experience',\n",
        "    'blue_global_draft_wr', 'red_global_draft_wr',\n",
        "    'blue_ban_disruption', 'red_ban_disruption',\n",
        "    'blue_buffs_in_draft', 'blue_nerfs_in_draft',\n",
        "    'red_buffs_in_draft',  'red_nerfs_in_draft',\n",
        "    'blue_momentum', 'red_momentum',\n",
        "    'blue_h2h_winrate',\n",
        "    'blue_patch_practice', 'red_patch_practice',\n",
        "    'is_playoffs',\n",
        "    'blue_playoff_clutch', 'red_playoff_clutch',\n",
        "    'blue_playoff_exp', 'red_playoff_exp',\n",
        "    'blue_g3_clutch_wr', 'red_g3_clutch_wr',\n",
        "    'blue_reverse_sweep_rate', 'red_reverse_sweep_rate',\n",
        "    'blue_rest_factor', 'red_rest_factor',\n",
        "    'blue_avg_win_duration', 'red_avg_win_duration',\n",
        "    'current_blue_side_advantage'\n",
        "]\n",
        "\n",
        "df_g1 = df[df['game_number'] == 1].copy()\n",
        "df_g2plus = df[df['game_number'] > 1].copy()\n",
        "\n",
        "X_g1 = df_g1[base_features]; y_g1 = df_g1['target_blue_win']; w_g1 = df_g1['time_weight']\n",
        "X_g2plus = df_g2plus[base_features]; y_g2 = df_g2plus['target_blue_win']; w_g2 = df_g2plus['time_weight']\n",
        "\n",
        "print(f\"🤖 Training V7 Ensemble on {len(df)} games...\")\n",
        "model_g1 = xgb.XGBClassifier(n_estimators=100).fit(X_g1, y_g1, sample_weight=w_g1)\n",
        "model_g2 = xgb.XGBClassifier(n_estimators=100).fit(X_g2plus, y_g2, sample_weight=w_g2)\n",
        "\n",
        "print(\"🏆 V7 RESULTS:\")\n",
        "print(f\"   Game 1  Model Accuracy : {accuracy_score(y_g1, model_g1.predict(X_g1)):.2%}\")\n",
        "print(f\"   Game 2+ Model Accuracy : {accuracy_score(y_g2, model_g2.predict(X_g2plus)):.2%}\")\n"
    ]

    new_cells = [
        nbformat.v4.new_code_cell(setup_source, id='setup_cell'),
        nbformat.v4.new_code_cell(pipeline_source, id='pipeline_cell'),
        nbformat.v4.new_code_cell(modeling_source, id='modeling_cell')
    ]

    nb.cells = new_cells
    with open(nb_path, 'w') as f:
        nbformat.write(nb, f)

fix()
print('Notebook fixed successfully!')
